# Generated by Django 5.1.5 on 2025-02-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
    ]
