# Generated by Django 5.1.6 on 2025-03-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0006_remove_product_discount_price_and_more'),
    ]

    operations = [
    ]
