# Generated by Django 5.1.6 on 2025-03-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0009_alter_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
