# Generated by Django 5.2 on 2025-04-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0014_order_orderitem'),
        ('QuickMedsApp', '0015_product_stock'),
    ]

    operations = [
    ]
