# Generated by Django 5.2 on 2025-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0016_merge_0014_order_orderitem_0015_product_stock'),
    ]

    operations = [
        # Note: All fields already exist in database from 0001_initial
        # This migration was needed for SQLite but MySQL already has the correct schema
        # Skipping operations to avoid conflicts
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
