# Generated by Django 5.2 on 2025-04-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0019_contact_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
