# Generated by Django 5.1.5 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0021_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('REFUND_PENDING', 'Refund Pending')], default='PENDING', max_length=20),
        ),
    ]
