# Generated by Django 5.2 on 2025-04-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0022_checkoutsession_is_buy_now_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='is_buy_now',
        ),
    ]
