# Generated by Django 5.1.5 on 2025-10-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMedsApp', '0024_userprofile_dob_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
